packaging: dkms: rpm: Update post-install script
Update the post-install script to run to completion upon success instead
of exiting from within the loop. This enables adding additional
functionality.

This patch makes no functional change.

Signed-off-by: Ryno Swart <ryno.swart@corigine.com>
Reviewed-by: James Hershaw <james.hershaw@corigine.com>
Reviewed-by: Walter Heymans <walter.heymans@corigine.com>
Reviewed-by: Louis Peens <louis.peens@corigine.com>

diff --git a/.github/packaging/rpm/nfp-drv-kmods-dkms.spec.in b/.github/packaging/rpm/nfp-drv-kmods-dkms.spec.in
--- a/.github/packaging/rpm/nfp-drv-kmods-dkms.spec.in
+++ b/.github/packaging/rpm/nfp-drv-kmods-dkms.spec.in
@@ -79,18 +79,24 @@ if ! [ -d "/lib/modules/$(uname -r)/build" ]; then
         echo -e "The 'kernel-devel' package can be installed using:"
         echo -e "    ${PKG_MAN} install kernel-devel-\$(uname -r)"
 fi
+status=no_postinst
 for POSTINST in %{_datarootdir}/%{module_name}/postinst; do
         if [ -f $POSTINST ]; then
                 $POSTINST %{module_name} %{version}-%{release} %{_datarootdir}/%{module_name}
-                exit $?
+                status=$?
+                break
         fi
         echo "WARNING: $POSTINST does not exist."
 done
-echo -e "ERROR: DKMS version is too old and %{module_name} was not"
-echo -e "built with legacy DKMS support."
-echo -e "You must either rebuild %{module_name} with legacy postinst"
-echo -e "support or upgrade DKMS to a more current version."
-exit 1
+if [ $status == no_postinst ]; then
+        echo -e "ERROR: DKMS version is too old and %{module_name} was not"
+        echo -e "built with legacy DKMS support."
+        echo -e "You must either rebuild %{module_name} with legacy postinst"
+        echo -e "support or upgrade DKMS to a more current version."
+        status=1
+fi
+exit $status
+
 
 %preun
 echo -e
